name: widgetx
description: "Flutter Low-Code Platform - Professional drag-drop UI builder with AI-powered code generation"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1        # State management
  go_router: ^16.0.0              # Navigation
  freezed_annotation: 3.1.0     # Immutable models
  json_annotation: ^4.9.0         # JSON serialization
  flutter_colorpicker: ^1.1.0     # Color picker
  code_text_field: ^1.1.0         # Code editor
  flutter_highlight: ^0.7.0       # Syntax highlighting
  shared_preferences: ^2.5.3      # Local storage
  file_picker: ^10.2.0             # File operations
  archive: ^4.0.7                 # ZIP export
  uuid: ^4.5.1                    # Unique IDs
  dartx: ^1.2.0                   # Dart extensions
  cupertino_icons: ^1.0.8         # Icons
  google_fonts: ^6.2.1            # Typography
  flutter_staggered_grid_view: ^0.7.0  # Grid layouts
  reorderables: ^0.6.0            # Reorderable widgets
  flutter_animate: ^4.5.2         # Animations
  collection: ^1.19.1             # Collections
  path: ^1.9.1                    # Path utilities
  http: ^1.4.0                    # HTTP requests
  highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.6.0            # Code generation
  freezed: ^3.2.0                 # Model generation
  json_serializable: ^6.10.0      # JSON serialization
  flutter_lints: ^6.0.0           # Linting

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
